### ISSUE TITLE
Is there any feature to look up files on the subdirectories?

### ISSUE THREAD

**Issue by repomorphic** [piecioshka/encoding-checker#11]
Hi there. I am looking for a feature that allows to look up encoding of files on the sub-directories. Is there any command line parameter for that?

**Comment by piecioshka** [comment]
Install recent version https://github.com/piecioshka/encoding-checker/commit/cce7d4c8689dd314ac37b6a1b1e7be148ab5e078

Use command:

```bash
encoding-checker -p "**"
```

to get details about recursive files.
