### ISSUE TITLE
Error: Command failed @ Windows 7

### ISSUE THREAD

**Issue by diegomagikal** [piecioshka/encoding-checker#2]
Npm version 5.6.0

When I run `encoding-checker -d .` , I get this error:
`Command failed: find -f  . | xargs file -I" `
in 
`node_modules\encoding-checker\bin\index.js:51`
```
if (err) throw err;
           ^
```
what's wrong? Thks

**Comment by piecioshka** [comment]
OS?

**Comment by diegomagikal** [comment]
Windows 7 sp1

**Comment by piecioshka** [comment]
@diegomagikal Please share stacktrace.

**Comment by diegomagikal** [comment]
![e-checker](https://user-images.githubusercontent.com/16082344/35483386-0f46a830-0420-11e8-8baf-4425b223eb5a.JPG)

**Comment by piecioshka** [comment]
This is because your system doesn't have `find` command.
@diegomagikal Maybe you can try to create Pull Request where you use some kind of `find` pkg from npm?

**Comment by moldach** [comment]
I'm getting the same error on Centos-7 and I do have the `find` command. 

![image](https://user-images.githubusercontent.com/5749465/44679134-1a26a280-aa08-11e8-958a-d335220583f0.png)

Any idea where the problem may stem from? 

One possible issue may be the fact that I do not have root access. Therefore, I got IT to install `npm` globally on the cluster. Then, I followed the advice from [this website](https://docs.appcelerator.com/platform/latest/?mobile=/guide/Installing_Node) and set `npm` to install (new) programs to my home directory by adding the following to my `.bash_profile`: `export NPM_CONFIG_PREFIX=$HOME` and then `source .bash_profile`.

I noticed that your instructions for installing `encoding-checker` with `npm` used the `-g` flag which is for global installation. When I ran it as is it seems to work as it can access the `encoding-checker` program but fails when I run `encoding-checker -d .` (see above image).

When I use the `-l` local flag instead I get this error:

`moldach@cortex:~ $ npm install -l encoding-checker

│ /exports/meaney.lab/moldach
│
└─┬ encoding-checker@1.0.1
  │ Tool to investigate files with different encoding than passed
  │ git+ssh://git@github.com/piecioshka/encoding-checker.git
  │ https://github.com/piecioshka/encoding-checker#readme
  ├── colors@1.3.2
  │   get colors in your node.js console
  │   git+ssh://git@github.com/Marak/colors.js.git
  │   https://github.com/Marak/colors.js
  └── commander@2.17.1
      the complete solution for node.js command-line programs
      git+https://github.com/tj/commander.js.git
      https://github.com/tj/commander.js#readme

npm WARN enoent ENOENT: no such file or directory, open '/exports/meaney.lab/moldach/package.json'
npm WARN moldach No description
npm WARN moldach No repository field.
npm WARN moldach No README data
npm WARN moldach No license field.
`
Any idea what I should try? Thanks!

**Comment by piecioshka** [comment]
https://github.com/piecioshka/encoding-checker/pull/10

**Comment by piecioshka** [comment]
Windows 7 hasn't `file` command which I used to fetch info about encoding.

I put info about that in #10 .

**Comment by piecioshka** [comment]
Oh! With @rkaw92 we discus how add support to Windows, in #10 I just add lib `jschardet` which support that system.

@diegomagikal Please look at latest version of `encoding-checker` 😏

**Comment by diegomagikal** [comment]
@piecioshka Thanks! It works fine now.
